-- As admin
create user ouser identified by MyDB__12345678; 
grant create session,create table,create sequence  to ouser;
grant unlimited tablespace to ouser;

--
create or replace FUNCTION GET_GEOMETRY (
      IN_LONGITUDE NUMBER,
      IN_LATITUDE  NUMBER
  ) RETURN SDO_GEOMETRY
      DETERMINISTIC PARALLEL_ENABLE
  IS
  BEGIN
   IF (IN_LONGITUDE IS NOT NULL 
      AND IN_LONGITUDE BETWEEN -180 AND 180
      AND IN_LATITUDE IS NOT NULL 
      AND IN_LATITUDE BETWEEN -90 AND 90)
   THEN
    RETURN 
      SDO_GEOMETRY(
        2001, 
        4326, 
        SDO_POINT_TYPE(IN_LONGITUDE, IN_LATITUDE, NULL), 
        NULL, NULL);
    ELSE RETURN NULL;
    END IF;
  END;
 /
 
create or replace function "SGTECH_PTF"(longitude in number, 
                                      latitude in number)
return SDO_GEOMETRY deterministic is
begin
  if latitude is NULL or longitude is NULL or latitude not between -90 and 90 or longitude not between -180 and 180
  then
    return NULL;
  else
     return sdo_geometry(2001, 4326, 
                sdo_point_type(longitude, latitude, NULL),NULL, NULL);
  end if;
end;
/


CREATE INDEX "SPIDX_ONLINE_S"  ON ONLINE_STORES (GET_GEOMETRY("LONGITUDE","LATITUDE")) 
INDEXTYPE IS "MDSYS"."SPATIAL_INDEX_V2"  PARAMETERS ('layer_gtype=POINT cbtree_index=true');

--
CREATE TABLE  "ONLINE_STORES"(    
  "PK_COL" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
  "LATITUDE" NUMBER,
  "LONGITUDE" NUMBER,
  "PIN_CODE" NUMBER,
  "STORE_ADDRESS" VARCHAR2(256) COLLATE "USING_NLS_COMP",
  "STORE_NAME" VARCHAR2(64) COLLATE "USING_NLS_COMP",
  CONSTRAINT "ONLINE_STORES_1_PK" PRIMARY KEY ("PK_COL")
  USING INDEX  ENABLE
) 

INSERT INTO user_sdo_geom_metadata values (
  'ONLINE_STORES',
  'GET_GEOMETRY("LONGITUDE", "LATITUDE")',
  sdo_dim_array(
    sdo_dim_element('LONG', -180, 180, 0.5),
    sdo_dim_element('LAT', -90, 90, 0.5)
  ),
  4326
);

CREATE INDEX "OUSER"."SPIDX_ONLINE_S"  ON OUSER.ONLINE_STORES (GET_GEOMETRY("LONGITUDE","LATITUDE"))  INDEXTYPE IS "MDSYS"."SPATIAL_INDEX_V2"  PARAMETERS ('layer_gtype=POINT cbtree_index=true');

create index spidx_j_onlineorder on j_onlineorder (OUSER.GET_GEOMETRY(OO_DOCUMENT)) indextype is mdsys.spatial_index_v2;

--
grant execute on get_geometry to ouser;
grant execute on sgtech_ptf to ouser;

-- 

connect ouser/MyDB__12345678



-- As Ouser
create or replace function get_geometry (json varchar2)
return sdo_geometry deterministic is
begin
  return sdo_geometry (
    2001, 4326, 
    sdo_point_type (json_value(json, '$.LONGITUDE'),json_value(json, '$.LATITUDE'),null),
    null, null
  );
end;
/ 
​
INSERT INTO user_sdo_geom_metadata values (
  'J_ONLINEORDER',
  'OUSER.GET_GEOMETRY(OO_DOCUMENT)',
  sdo_dim_array(
    sdo_dim_element('LONG', -180, 180, 0.5),
    sdo_dim_element('LAT', -90, 90, 0.5)
  ),
  4326
);
​
​
create index spidx_j_onlineorder on j_onlineorder (OUSER.GET_GEOMETRY(OO_DOCUMENT)) indextype is mdsys.spatial_index_v2;




insert into user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
values (
  'ONLINE_STORES',
  'OUSER.GET_GEOMETRY("LONGITUDE","LATITUDE")',
  sdo_dim_array(
    sdo_dim_element ('Longitude', -180, 180, 0.5),
    sdo_dim_element ('Latitude', -90, 90, 0.5)
  ),
  4326
);

CREATE INDEX "SPIDX_ONLINE_S" ON ONLINE_STORES (GET_GEOMETRY("LONGITUDE","LATITUDE")) INDEXTYPE IS "MDSYS"."SPATIAL_INDEX_V2"  PARAMETERS ('layer_gtype=POINT cbtree_index=true');


create or replace function get_geometry_oo (json varchar2)
return sdo_geometry deterministic is
begin
  return sdo_geometry (
    2001, 4326, 
    sdo_point_type (json_value(json, '$.LONGITUDE'),json_value(json, '$.LATITUDE'),null),
    null, null
  );
end;
/ 
​
INSERT INTO user_sdo_geom_metadata values (
  'J_ONLINEORDER',
  'OUSER.GET_GEOMETRY_OO(OO_DOCUMENT)',
  sdo_dim_array(
    sdo_dim_element('LONG', -180, 180, 0.5),
    sdo_dim_element('LAT', -90, 90, 0.5)
  ),
  4326
);

create index spidx_j_onlineorder on j_onlineorder (OUSER.get_geometry_oo(OO_DOCUMENT)) indextype is mdsys.spatial_index_v2;