create user ouser identified by BotWelcome123##; 
grant create session,create table,create sequence  to ouser;
grant unlimited tablespace to ouser;
grant CREATE MINING MODEL, CREATE TABLE, CREATE VIEW TO ouser;

CREATE TABLE  "ONLINEORDER" 
   (	"COUNTRY_CODE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"ORDER_DATETIME" TIMESTAMP (6), 
	"LINE_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"QUANTITY" NUMBER, 
	"ITEM_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"AMOUNT" NUMBER, 
	"ORDER_ID" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "CUSTOMERORDER" 
   (	"NAME" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"PHONE" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"LOCATION" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"CARD" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CODE" VARCHAR2(50) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "ONLINE_STORES" 
   (	"PK_COL" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"LATITUDE" NUMBER, 
	"LONGITUDE" NUMBER, 
	"PIN_CODE" NUMBER, 
	"STORE_ADDRESS" VARCHAR2(256) COLLATE "USING_NLS_COMP", 
	"STORE_NAME" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"COUNTRY_CODE" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	 CONSTRAINT "ONLINE_STORES_1_PK" PRIMARY KEY ("PK_COL")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/

insert into ONLINE_STORES(country_code, pk_col, pin_code, store_address, store_name, LATITUDE, LONGITUDE) VALUES ('SGP', 110, 247911, '29 Tanglin Road, Lobby Floor, St. Regis Hotel, Singapore 247911', 'yellowstore',1.3428,103.8854);
insert into ONLINE_STORES(country_code, pk_col, pin_code, store_address, store_name, LATITUDE, LONGITUDE) VALUES ('SGP', 4, 178882, '122 Windsor Park Rd, Singapore 574182', 'bluestore', 1.3557, 103.8243);
insert into ONLINE_STORES(country_code, pk_col, pin_code, store_address, store_name, LATITUDE, LONGITUDE) VALUES ('AUS', 97, 228208, '204 Sussex St, Sydney NSW 2000, Australia', 'freshstore', -33.8714, 151.2043);
insert into ONLINE_STORES(country_code, pk_col, pin_code, store_address, store_name, LATITUDE, LONGITUDE) VALUES ('AUS', 48, 88461, '163 Crown St, Darlinghurst NSW 2010, Australia', 'seastore', -33.8768, 151.2155);
insert into ONLINE_STORES(country_code, pk_col, pin_code, store_address, store_name, LATITUDE, LONGITUDE) VALUES ('IND', 53, 18972, 'MTNL Rd, Saki Naka, Mumbai, Maharashtra 400072, India', 'organicstore', 19.1005, 72.8812);
insert into ONLINE_STORES(country_code, pk_col, pin_code, store_address, store_name, LATITUDE, LONGITUDE) VALUES ('IND', 50, 18956, '3RGW+7XH Mumbai, Maharashtra, India', 'onlinestore', 19.0757, 72.8475);
commit;

insert into user_sdo_geom_metadata (table_name, column_name, diminfo, srid)
values (
  'ONLINE_STORES',
  'OUSER.GET_GEOMETRY("LONGITUDE","LATITUDE")',
  sdo_dim_array(
    sdo_dim_element ('Longitude', -180, 180, 0.5),
    sdo_dim_element ('Latitude', -90, 90, 0.5)
  ),
  4326
);
commit;


create or replace FUNCTION GET_GEOMETRY (
      IN_LONGITUDE NUMBER,
      IN_LATITUDE  NUMBER
  ) RETURN SDO_GEOMETRY
      DETERMINISTIC PARALLEL_ENABLE
  IS
  BEGIN
   IF (IN_LONGITUDE IS NOT NULL 
      AND IN_LONGITUDE BETWEEN -180 AND 180
      AND IN_LATITUDE IS NOT NULL 
      AND IN_LATITUDE BETWEEN -90 AND 90)
   THEN
    RETURN 
      SDO_GEOMETRY(
        2001, 
        4326, 
        SDO_POINT_TYPE(IN_LONGITUDE, IN_LATITUDE, NULL), 
        NULL, NULL);
    ELSE RETURN NULL;
    END IF;
  END;
 /

CREATE INDEX "SPIDX_ONLINE_S" ON ONLINE_STORES (GET_GEOMETRY("LONGITUDE","LATITUDE")) INDEXTYPE IS "MDSYS"."SPATIAL_INDEX_V2"  PARAMETERS ('layer_gtype=POINT cbtree_index=true');
/

